tests for basic functions
mixdone/terraform-provider-virtualbox pull request #13
Opened 2023-11-11 17:16 UTC by daria-barsukova

2023-11-11 19:11 UTC, fojnk reviewed
В общем 1 и 4 тесты у меня работают, 2 и 3 - ломаются, завтра еще раз посмотрю

2023-11-12 07:14 UTC, fojnk requested changes

2023-11-12 07:14 UTC, fojnk commented on terraform-provider-virtualbox/internal/provider/VM_test.go
> +	dirName, err := os.MkdirTemp("./", "VirtualBox VMs")
Ошибку нашел, используй здесь os.UserHomeDir вместо ./, все же не лучшая практика создавать папки виртуальных машин в нашем провайдере)

2023-11-12 07:14 UTC, fojnk commented on terraform-provider-virtualbox/internal/provider/VM_test.go
> +	dirName, err := os.MkdirTemp("./", "VirtualBox VMs")
os.UserHomeDir

2023-11-12 07:15 UTC, fojnk commented on terraform-provider-virtualbox/internal/provider/VM_test.go
> +	dirName, err := os.MkdirTemp("./", "VirtualBox VMs")
в остальном молодец, по крайней мере после исправления тесты работают

2023-11-12 09:50 UTC, daria-barsukova commented
`os.UserHomeDir вместо ./` имелось в виду то, что я добавила, или что-то другое?

2023-11-12 14:34 UTC, fojnk approved these changes

2023-11-12 14:35 UTC, merged