try to fix
mixdone/terraform-provider-virtualbox pull request #27
Opened 2023-12-01 05:10 UTC by an-mrv

2023-12-01 12:45 UTC, an-mrv commented
Пока пришлось закомментировать весь первый тест, надо будет его пофиксить

2023-12-02 15:06 UTC, fojnk requested changes

2023-12-02 15:06 UTC, fojnk commented on internal/provider/VM_test.go
> +	var ltype pkg.LoadingType = 2
Сори, что не прописал комментом. Этот тип создает машину без дисков, т.е по сути url, которой ты передаешь, вообще никакой роли не играет.

2023-12-02 15:24 UTC, an-mrv commented on internal/provider/VM_test.go
> +	time.AfterFunc(3*time.Second, func() {
Эту конструкцию пришлось добавить, потому что тест не укладывается в 30 секунд таймаута и из-за этого падает, тогда еще поищу как это изменить

2023-12-02 16:34 UTC, fojnk commented on internal/provider/VM_test.go
> +	time.AfterFunc(3*time.Second, func() {
да, я понял, что в этом проблема, но пока только на уровне компиляции тестов решение нашел.Хотя это не совсем то, что нам нужно.

2023-12-02 16:35 UTC, fojnk commented on internal/provider/VM_test.go
> +	time.AfterFunc(3*time.Second, func() {
Можешь взять архив размером поменьше, в целом нам не критично именно скачивание диска проверять.

2023-12-02 16:38 UTC, an-mrv commented on internal/provider/VM_test.go
> +		if _, err := os.Stat(filepath.Join(homedir, "ubuntu-15.04.vdi")); err != nil {
Здесь из-за того, что я распаковываю архив в домашнюю директорию, а не в папку с виртуальной машиной, то последний параметр пути получается неправильный

2023-12-06 02:33 UTC, merged